version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: riv-dev-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: riv-dev-mailhog
    ports:
      - '1025:1025'  # SMTP port
      - '8025:8025'  # Web UI port
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/maildir
      - MH_SMTP_BIND_ADDR=0.0.0.0:1025
      - MH_UI_BIND_ADDR=0.0.0.0:8025
    volumes:
      - mailhog_data:/maildir
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:8025']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
  mailhog_data:
